// src/components/modals/CompanyModal.tsx
"use client";

import { useEffect, useState } from "react";
import ModalProps from "@/interfaces/ModalProps";
import Cookies from "js-cookie";
import Company from "@/interfaces/Company";
import axiosInstance from "@/lib/axios";

interface CompanyModalProps extends ModalProps {
  id: string;
  userRole: string; // Injected from parent
}

const CompanyModal = ({ id, onClose, onSave, userRole }: CompanyModalProps) => {
  const [formData, setFormData] = useState<Partial<Company>>({});
  const token = Cookies.get('sempoa');

  useEffect(() => {
    if (!id) return;
    const fetchBasicData = async () => {
      try {
        const res = await axiosInstance.get(`/companies/${id}`, {
          headers: { Authorization : `Bearer ${token}` }
        });
        setFormData({
          ...res.data,
          status: res.data.status || "development",
        });
      } catch (err) {
        console.error("Failed to fetch company detail", err);
      }
    };
    fetchBasicData();
  }, [id]);

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const payload = { ...formData };
    onSave(payload as Company);
  };

  return (
    <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
      <div className="bg-white p-6 rounded shadow-lg w-8/12">
        <h2 className="text-xl font-bold mb-4">{formData?.id ? "Edit" : "Create"} Company</h2>
        <form onSubmit={handleSubmit}>
          {/* Company Name */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Company Name</label>
            <input
              type="text"
              name="companyName"
              value={formData?.companyName || ""}
              onChange={handleChange}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            />
          </div>

          {/* Trading Name */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Trading Name</label>
            <input
              type="text"
              name="tradingName"
              value={formData?.tradingName || ""}
              onChange={handleChange}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            />
          </div>

          {/* Company Code */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Company Code</label>
            <input
              type="text"
              name="companyCode"
              value={formData?.companyCode || ""}
              onChange={handleChange}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            />
          </div>

          {/* Address */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Address</label>
            <textarea
              name="address"
              value={formData?.address || ""}
              onChange={handleChange}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            ></textarea>
          </div>

          {/* Email */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Email</label>
            <input
              type="text"
              name="email"
              value={formData?.email || ""}
              onChange={handleChange}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            />
          </div>

          {/* Phone Number */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Phone Number</label>
            <input
              type="text"
              name="phoneNumber"
              value={formData?.phoneNumber || ""}
              onChange={handleChange}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            />
          </div>

          {/* Buttons */}
          <div className="flex justify-end">
            <button type="button" onClick={onClose} className="px-4 py-2 bg-gray-300 rounded hover:bg-gray-400 mr-2">
              Cancel
            </button>
            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
              Save
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CompanyModal;

// src/components/modals/CompanyModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { toast } from 'vue-sonner'
import AppDialog from '@/components/ui/AppDialog.vue'
import axiosInstance from '@/lib/axios'
import type { Company } from '@/interfaces/Company'

const props = defineProps<{ open: boolean; data: Company | null }>()
const emit = defineEmits<{ close: []; saved: [c: Company] }>()

const form = ref({ companyCode: '', companyName: '', tradingName: '', address: '', email: '', phoneNumber: '' })
const adminForm = ref({ name: '', email: '', password: '', phoneNumber: '' })
const saving = ref(false)

watch(() => props.data, v => {
  form.value = v
    ? { companyCode: v.companyCode, companyName: v.companyName, tradingName: v.tradingName, address: v.address, email: v.email, phoneNumber: v.phoneNumber }
    : { companyCode: '', companyName: '', tradingName: '', address: '', email: '', phoneNumber: '' }
  adminForm.value = { name: '', email: '', password: '', phoneNumber: '' }
}, { immediate: true })

async function submit() {
  saving.value = true
  try {
    const res = props.data?.id
      ? await axiosInstance.patch(`/companies/${props.data.id}`, form.value)
      : await axiosInstance.post('/companies', form.value)

    if (!props.data?.id) {
      // Create the company admin user
      await axiosInstance.post('/users', {
        ...adminForm.value,
        companyId: res.data.id,
        role: 'company_admin',
      })
    }

    toast.success(props.data?.id ? 'Updated' : 'Company and admin user created')
    emit('saved', res.data)
  } catch (e: any) {
    toast.error(e?.response?.data?.message ?? 'Save failed')
  } finally { saving.value = false }
}
</script>

<template>
  <AppDialog :open="open" :title="data?.id ? 'Edit Company' : 'New Company'" @close="emit('close')">
    <form @submit.prevent="submit" class="space-y-4">
      <div class="grid grid-cols-2 gap-4">
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Code *</label>
          <input v-model="form.companyCode" required class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Company Name *</label>
          <input v-model="form.companyName" required class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Trading Name</label>
          <input v-model="form.tradingName" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Email</label>
          <input v-model="form.email" type="email" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Phone</label>
          <input v-model="form.phoneNumber" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
        <div class="space-y-1.5 col-span-2">
          <label class="text-[13px] font-medium text-nav-text">Address</label>
          <textarea v-model="form.address" rows="2" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
      </div>

      <template v-if="!data?.id">
          <div class="border-t border-sidebar-border pt-4">
          <p class="text-[13px] font-semibold text-heading mb-3">Company Admin User</p>
          <div class="grid grid-cols-2 gap-4">
            <div class="space-y-1.5">
              <label class="text-[13px] font-medium text-nav-text">Full Name *</label>
              <input v-model="adminForm.name" required class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
            </div>
            <div class="space-y-1.5">
              <label class="text-[13px] font-medium text-nav-text">Email *</label>
              <input v-model="adminForm.email" type="email" required class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
            </div>
            <div class="space-y-1.5">
              <label class="text-[13px] font-medium text-nav-text">Password *</label>
              <input v-model="adminForm.password" type="password" required minlength="8" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
            </div>
            <div class="space-y-1.5">
              <label class="text-[13px] font-medium text-nav-text">Phone</label>
              <input v-model="adminForm.phoneNumber" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
            </div>
          </div>
        </div>
      </template>

      <div class="flex justify-end gap-2 pt-2">
        <button type="button" @click="emit('close')" class="px-4 py-2 text-[13px] border border-sidebar-border rounded hover:bg-sidebar-panel transition-colors text-nav-text">Cancel</button>
        <button type="submit" :disabled="saving" class="px-4 py-2 text-[13px] bg-brand hover:bg-brand-light text-white rounded transition-colors disabled:opacity-50">{{ saving ? 'Saving…' : 'Save' }}</button>
      </div>
    </form>
  </AppDialog>
</template>
