// src/components/modals/ProjectModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { toast } from 'vue-sonner'
import AppDialog from '@/components/ui/AppDialog.vue'
import axiosInstance from '@/lib/axios'
import type { Project } from '@/interfaces/Project'

const props = defineProps<{ open: boolean; data: Project | null }>()
const emit = defineEmits<{ close: []; saved: [p: Project] }>()

const form = ref({ projectCode: '', projectName: '', description: '' })
const saving = ref(false)

watch(() => props.data, v => {
  form.value = v ? { projectCode: v.projectCode, projectName: v.projectName, description: v.description ?? '' } : { projectCode: '', projectName: '', description: '' }
}, { immediate: true })

async function submit() {
  saving.value = true
  try {
    const res = props.data?.id
      ? await axiosInstance.patch(`/projects/${props.data.id}`, form.value)
      : await axiosInstance.post('/projects', form.value)
    toast.success(props.data?.id ? 'Updated' : 'Created')
    emit('saved', res.data)
  } catch (e: any) {
    toast.error(e?.response?.data?.message ?? 'Save failed')
  } finally { saving.value = false }
}
</script>

<template>
  <AppDialog :open="open" :title="data?.id ? 'Edit Project' : 'New Project'" @close="emit('close')">
    <form @submit.prevent="submit" class="space-y-4">
      <div class="space-y-1.5">
        <label class="text-[13px] font-medium text-nav-text">Project Code *</label>
        <input v-model="form.projectCode" required class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
      </div>
      <div class="space-y-1.5">
        <label class="text-[13px] font-medium text-nav-text">Project Name *</label>
        <input v-model="form.projectName" required class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
      </div>
      <div class="space-y-1.5">
        <label class="text-[13px] font-medium text-nav-text">Description</label>
        <textarea v-model="form.description" rows="3" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
      </div>
      <div class="flex justify-end gap-2 pt-2">
        <button type="button" @click="emit('close')" class="px-4 py-2 text-[13px] border border-sidebar-border rounded hover:bg-sidebar-panel transition-colors text-nav-text">Cancel</button>
        <button type="submit" :disabled="saving" class="px-4 py-2 text-[13px] bg-brand hover:bg-brand-light text-white rounded transition-colors disabled:opacity-50">{{ saving ? 'Saving…' : 'Save' }}</button>
      </div>
    </form>
  </AppDialog>
</template>

// src/components/modals/ProjectModal.tsx
"use client";

import { useEffect, useState } from "react";
import ModalProps from "@/interfaces/ModalProps";
import Cookies from "js-cookie";
import Project from "@/interfaces/Project";
import axiosInstance from "@/lib/axios";

interface ProjectModalProps extends ModalProps {
  id: string;
  userRole: string; // Injected from parent
}

const ProjectModal = ({ id, onClose, onSave, userRole }: ProjectModalProps) => {
  const [formData, setFormData] = useState<Partial<Project>>({});
  const token = Cookies.get('sempoa');

  useEffect(() => {
    if (!id) return;
    const fetchBasicData = async () => {
      try {
        const res = await axiosInstance.get(`/projects/${id}`, {
          headers: { Authorization : `Bearer ${token}` }
        });
        setFormData({
          ...res.data,
          status: res.data.status || "development",
        });
      } catch (err) {
        console.error("Failed to fetch project detail", err);
      }
    };
    fetchBasicData();
  }, [id]);

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const payload = { ...formData };
    onSave(payload as Project);
  };

  return (
    <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
      <div className="bg-white p-6 rounded shadow-lg w-8/12">
        <h2 className="text-xl font-bold mb-4">{formData?.id ? "Edit" : "Create"} Project</h2>
        <form onSubmit={handleSubmit}>
          {/* Project Name */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Project Name</label>
            <input
              type="text"
              name="projectName"
              value={formData?.projectName || ""}
              onChange={handleChange}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            />
          </div>

          {/* Trading Name */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Project Code</label>
            <input
              type="text"
              name="projectCode"
              value={formData?.projectCode || ""}
              onChange={handleChange}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            />
          </div>

          {/* Description */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Description</label>
            <textarea
              name="description"
              value={formData?.description || ""}
              onChange={handleChange}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            ></textarea>
          </div>

          {/* Buttons */}
          <div className="flex justify-end">
            <button type="button" onClick={onClose} className="px-4 py-2 bg-gray-300 rounded hover:bg-gray-400 mr-2">
              Cancel
            </button>
            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
              Save
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ProjectModal;
