// src/components/modals/UserModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { toast } from 'vue-sonner'
import AppDialog from '@/components/ui/AppDialog.vue'
import axiosInstance from '@/lib/axios'
import type { User } from '@/interfaces/User'

const props = defineProps<{ open: boolean; data: User | null; companyId: string }>()
const emit = defineEmits<{ close: []; saved: [u: User] }>()

const form = ref({ name: '', email: '', phoneNumber: '', role: 'user', status: 'active', password: '' })
const saving = ref(false)

watch(() => props.data, v => {
  form.value = v
    ? { name: v.name, email: v.email, phoneNumber: v.phoneNumber, role: v.role, status: v.status, password: '' }
    : { name: '', email: '', phoneNumber: '', role: 'user', status: 'active', password: '' }
}, { immediate: true })

async function submit() {
  saving.value = true
  try {
    let res
    if (props.data?.id) {
      const payload: any = { name: form.value.name, email: form.value.email, phoneNumber: form.value.phoneNumber, role: form.value.role, status: form.value.status }
      if (form.value.password) payload.password = form.value.password
      res = await axiosInstance.patch(`/users/${props.data.id}`, payload)
    } else {
      res = await axiosInstance.post('/users', { ...form.value, companyId: props.companyId })
    }
    toast.success(props.data?.id ? 'Updated' : 'Created')
    emit('saved', res.data)
  } catch (e: any) {
    toast.error(e?.response?.data?.message ?? 'Save failed')
  } finally { saving.value = false }
}
</script>

<template>
  <AppDialog :open="open" :title="data?.id ? 'Edit User' : 'New User'" @close="emit('close')">
    <form @submit.prevent="submit" class="space-y-4">
      <div class="grid grid-cols-2 gap-4">
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Name *</label>
          <input v-model="form.name" required class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Email *</label>
          <input v-model="form.email" type="email" required class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Phone</label>
          <input v-model="form.phoneNumber" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Role</label>
          <select v-model="form.role" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors">
            <option value="super_admin">Super Admin</option>
            <option value="ops_admin">Ops Admin</option>
            <option value="company_admin">Company Admin</option>
            <option value="manager">Manager</option>
            <option value="user">User</option>
          </select>
        </div>
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Status</label>
          <select v-model="form.status" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors">
            <option value="active">Active</option>
            <option value="disabled">Disabled</option>
          </select>
        </div>
        <div class="space-y-1.5">
          <label class="text-[13px] font-medium text-nav-text">Password {{ data?.id ? '(blank = keep)' : '*' }}</label>
          <input v-model="form.password" type="password" :required="!data?.id" class="w-full border border-sidebar-border rounded px-3 py-2 text-[13px] text-body-text focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand/30 transition-colors" />
        </div>
      </div>
      <div class="flex justify-end gap-2 pt-2">
        <button type="button" @click="emit('close')" class="px-4 py-2 text-[13px] border border-sidebar-border rounded hover:bg-sidebar-panel transition-colors text-nav-text">Cancel</button>
        <button type="submit" :disabled="saving" class="px-4 py-2 text-[13px] bg-brand hover:bg-brand-light text-white rounded transition-colors disabled:opacity-50">{{ saving ? 'Saving…' : 'Save' }}</button>
      </div>
    </form>
  </AppDialog>
</template>

// src/components/modals/UserModal.tsx
"use client";

import ModalProps from "@/interfaces/ModalProps";
import User from "@/interfaces/User";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useEffect, useState } from "react";
import Cookies from 'js-cookie';
import axiosInstance from "@/lib/axios";

const UserModal = ({ data, onClose, onSave }: ModalProps & { onSave?: () => void }) => {
  const [formData, setFormData] = useState<User | null>(data || null);
  const [confirmPassword, setConfirmPassword] = useState<string>('');
  const [errors, setErrors] = useState<{ [key: string]: string }>({});
  const [showPasswordFields, setShowPasswordFields] = useState(false);

  useEffect(() => {
    setFormData(data);
  }
  , [])

  const isNewUser = !formData?.id;

const handleSave = async () => {
  if (!formData) return;

  const { name, email, password, role } = formData;
  const newErrors: { [key: string]: string } = {};

  if (!name) newErrors.name = 'Name is required';
  if (!email) {
    newErrors.email = 'Email is required';
  } else {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      newErrors.email = 'Invalid email format';
    }
  }
  if (!role) {
    newErrors.role = 'Role is required';
  }

  if (isNewUser || showPasswordFields) {
    if (!password) {
      newErrors.password = 'Password is required';
    } else {
      const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/;
      if (!passwordRegex.test(password)) {
        newErrors.password = 'Must contain uppercase, lowercase, number, and be at least 8 characters';
      }
    }

    if (password !== confirmPassword) {
      newErrors.confirmPassword = 'Passwords do not match';
    }
  }

  if (Object.keys(newErrors).length > 0) {
    setErrors(newErrors);
    return;
  }

  setErrors({});
  const url = isNewUser ? `/users` : `/users/${formData.id}`;
  const method = isNewUser ? 'POST' : 'PATCH';
  const token = Cookies.get('sempoa');

  try {
    const { id, ...rest } = formData;
    const payload = isNewUser ? rest : { id, ...rest };

    await axiosInstance({
      method,
      url,
      data: payload,
      headers: { 'Authorization': `Bearer ${token}` },
    });

    onSave?.();
    onClose();
  } catch (error) {
    console.error('Error saving user:', error);
  }
};

  return (
    <Dialog open={true} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle>User</DialogTitle>
        </DialogHeader>
        <form>
          {/* Company Id */}
          <input type="hidden" value={data.companyId || ''} />

          {/* Name */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Name<span className="text-red-500">*</span></label>
            <input
              type="text"
              name="name"
              value={formData?.name || ""}
              onChange={(e) => setFormData(prev => prev ? { ...prev, name: e.target.value } : prev)}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            {errors.name && <p className="text-red-500 text-sm mt-1">{errors.name}</p>}
          </div>

          {/* Email */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Email<span className="text-red-500">*</span></label>
            <input
              type="text"
              name="email"
              value={formData?.email || ""}
              onChange={(e) => setFormData(prev => prev ? { ...prev, email: e.target.value } : prev)}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            {errors.email && <p className="text-red-500 text-sm mt-1">{errors.email}</p>}
          </div>

          {/* Phone */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Phone</label>
            <input
              type="text"
              name="phoneNumber"
              value={formData?.phoneNumber || ""}
              onChange={(e) => setFormData(prev => prev ? { ...prev, phoneNumber: e.target.value } : prev)}
              className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          {/* Role */}
          <div className="mb-4">
            <label className="block text-sm font-medium mb-2">Role<span className="text-red-500">*</span></label>
            <select
              name="role"
              value={formData?.role || ""}
              onChange={(e) => setFormData(prev => prev ? { ...prev, role: e.target.value } : prev)}
              className="w-full px-3 py-2 border rounded bg-gray-100"
            >
              <option value="">-- Select Role --</option>
              <option value="super">Super Admin</option>
              <option value="ops">Ops Admin</option>
              <option value="admin">Company Admin</option>
              <option value="user">User</option>
            </select>
            {errors.role && <p className="text-red-500 text-sm mt-1">{errors.role}</p>}
          </div>

          {!isNewUser && !showPasswordFields && (
            <div className="mb-4">
              <button
                type="button"
                className="text-sm text-blue-600 hover:underline"
                onClick={() => setShowPasswordFields(true)}
              >
                Change Password
              </button>
            </div>
          )}

          {(isNewUser || showPasswordFields) && (
            <>
              {/* Password */}
              <div className="mb-4">
                <label className="block text-sm font-medium mb-2">
                  Password<span className="text-red-500">*</span>
                </label>
                <input
                  type="password"
                  name="password"
                  className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                  onChange={(e) =>
                    setFormData((prev) => (prev ? { ...prev, password: e.target.value } : prev))
                  }
                />
                {errors.password && <p className="text-red-500 text-sm mt-1">{errors.password}</p>}
              </div>

              {/* Confirm Password */}
              <div className="mb-4">
                <label className="block text-sm font-medium mb-2">
                  Confirm Password<span className="text-red-500">*</span>
                </label>
                <input
                  type="password"
                  name="confirm"
                  value={confirmPassword}
                  className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                  onChange={(e) => setConfirmPassword(e.target.value)}
                />
                {errors.confirmPassword && (
                  <p className="text-red-500 text-sm mt-1">{errors.confirmPassword}</p>
                )}
              </div>
            </>
          )}

          {/* Buttons */}
          <div className="flex justify-end">
            <button type="button" onClick={onClose} className="px-4 py-2 bg-gray-300 rounded hover:bg-gray-400 mr-2">
              Cancel
            </button>
            <button type="button" onClick={handleSave} className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
              Save
            </button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default UserModal;
