// src/components/tables/ProjectFieldTable.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Pencil, Trash2 } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import BackofficeDataTable from './BackofficeDataTable.vue'
import ProjectFieldModal from '@/components/modals/ProjectFieldModal.vue'
import axiosInstance from '@/lib/axios'
import type { ProjectField } from '@/interfaces/ProjectField'

const props = defineProps<{ initialData: ProjectField[]; projectId: string; userRole?: string }>()
const data = ref<ProjectField[]>([...props.initialData])
const modalOpen = ref(false)
const selected = ref<ProjectField | null>(null)

const columns = [
  { key: 'fieldCode', label: 'Code' },
  { key: 'fieldText', label: 'Label' },
  { key: 'type', label: 'Type' },
  { key: 'visible', label: 'Visible' },
  { key: 'mandatory', label: 'Req.' },
  { key: 'sequence', label: 'Seq' },
  { key: 'actions', label: '' },
]

function openCreate() { selected.value = null; modalOpen.value = true }
function openEdit(f: ProjectField) { selected.value = f; modalOpen.value = true }

async function remove(f: ProjectField) {
  if (f.isSystem) { toast.error('Cannot delete system fields'); return }
  if (!confirm('Delete this field?')) return
  try {
    await axiosInstance.delete(`/project-fields/${f.id}`)
    data.value = data.value.filter(x => x.id !== f.id)
    toast.success('Field deleted')
  } catch { toast.error('Failed to delete') }
}

function onSaved(f: ProjectField) {
  const i = data.value.findIndex(x => x.id === f.id)
  if (i >= 0) data.value[i] = f; else data.value.push(f)
  modalOpen.value = false
}
</script>

<template>
  <div>
    <BackofficeDataTable :data="data as any" :columns="columns">
      <template #actions>
        <button @click="openCreate" class="px-3.5 py-1.5 bg-brand hover:bg-brand-light text-white text-[13px] rounded transition-colors">+ New Field</button>
      </template>
      <template #row="{ row }">
        <td class="px-4 py-3 font-mono text-[11px] font-medium text-m-muted">{{ row.fieldCode }}</td>
        <td class="px-4 py-3 text-body-text">{{ row.fieldText }}</td>
        <td class="px-4 py-3">
          <span class="px-2 py-0.5 bg-sidebar-panel text-nav-text border border-sidebar-border rounded text-[11px]">{{ row.type }}</span>
        </td>
        <td class="px-4 py-3 text-center">
          <span :class="row.visible ? 'text-green-500' : 'text-sidebar-border'">{{ row.visible ? '●' : '○' }}</span>
        </td>
        <td class="px-4 py-3 text-center">
          <span :class="row.mandatory ? 'text-green-500' : 'text-sidebar-border'">{{ row.mandatory ? '●' : '○' }}</span>
        </td>
        <td class="px-4 py-3 text-center text-m-muted">{{ row.sequence }}</td>
        <td class="px-4 py-3">
          <div class="flex items-center gap-1">
            <button @click="openEdit(row as any)"
              class="p-1.5 text-m-muted hover:text-nav-active rounded hover:bg-sidebar-panel transition-colors"><Pencil class="w-4 h-4" /></button>
            <button @click="remove(row as any)" :disabled="!!(row as any).isSystem"
              class="p-1.5 text-m-muted hover:text-red-500 rounded hover:bg-red-50 transition-colors disabled:opacity-25 disabled:cursor-not-allowed"><Trash2 class="w-4 h-4" /></button>
          </div>
        </td>
      </template>
    </BackofficeDataTable>
    <ProjectFieldModal :open="modalOpen" :data="selected" :project-id="projectId" @close="modalOpen = false" @saved="onSaved" />
  </div>
</template>

// src/components/tables/ProjectFieldTable.tsx
'use client';

import { useState } from 'react';
import Cookies from 'js-cookie';
import { Pencil, Trash2, PlusCircle } from 'lucide-react';
import { BackofficeDataTable } from "@/components/tables/BackofficeDataTable";
import { ColumnDef } from "@tanstack/react-table";
import { useRouter } from 'next/navigation';
import ProjectField from '@/interfaces/ProjectField';
import ProjectFieldModal from '../modals/ProjectFieldModal';
import axiosInstance from '@/lib/axios';

interface Props {
  initialData: ProjectField[];
  userRole: string;
  projectId: string;
}

export default function ProjectFieldTable({ initialData, userRole, projectId }: Props) {
  const [data, setData] = useState(initialData);
  // const [totalRows, setTotalRows] = useState(initialTotalRows);
  const [loading, setLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalData, setModalData] = useState<ProjectField | null>(null);
  // const [pageSize, setPageSize] = useState(10);
  // const [pageIndex, setPageIndex] = useState(0);
  const router = useRouter();

  const token = Cookies.get('sempoa');

  const columns: ColumnDef<ProjectField>[] = [
    {
      header: 'Field Code',
      accessorKey: 'fieldCode',
    },
    {
      header: 'Field Text',
      accessorKey: 'fieldText',
    },
    {
      header: 'Type',
      accessorKey: 'type',
    },
    {
      header: 'Visible',
      accessorKey: 'visible',
    },
    {
      header: 'Mandatory',
      accessorKey: 'mandatory',
    },
    {
      header: 'Sequence',
      accessorKey: 'sequence',
    },
    {
      header: 'Actions',
      cell: ({ row }) => (
        <div>
          {!row.original.isSystem && (
            <>
              <button
                onClick={() => {
                  setModalData(row.original);
                  setIsModalOpen(true);
                }}
                className="text-blue-500 hover:text-blue-700 p-2 border rounded border-gray-200 mr-2"
              >
                <Pencil className="w-4 h-4" />
              </button>
              <button
                onClick={() => handleDisable(row.original.id)}
                className="text-red-500 hover:text-red-700 p-2 border rounded border-gray-200 mr-2"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </>
          )}
        </div>
      ),
    },
  ];

  const handleAddEdit = async (field: ProjectField) => {
    const endpoint = field.id
      ? `/project-fields/${field.id}`
      : `/project-fields`;
    const method = field.id ? 'patch' : 'post';

    try {
      await axiosInstance[method](endpoint, field, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setIsModalOpen(false);
      fetchData();
    } catch (err) {
      console.error('Error saving:', err);
    }
  };

  const handleDisable = async (id: string) => {
    try {
      await axiosInstance.delete(`/project-fields/${id}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      fetchData();
    } catch (err) {
      console.error('Error deleting:', err);
    }
  };

  const fetchData = () => {
    setLoading(true);
    axiosInstance.get(`/project-fields?projectId=${projectId}`, {
      headers: { Authorization: `Bearer ${Cookies.get('sempoa')}` }
    })
      .then(res => {
        setData(res.data.data);
      })
      .catch(err => console.error('Get error:', err))
      .finally(() => setLoading(false));
  };

  // const handlePaginationChange: OnChangeFn<PaginationState> = (updater) => {
  //   const next = typeof updater === 'function' ? updater({ pageIndex, pageSize }) : updater;
  //   setPageIndex(next.pageIndex);
  //   setPageSize(next.pageSize);
  //   fetchData(next.pageIndex);
  // };

  return (
    <div className="w-full bg-white rounded-lg p-2">
      <button
        onClick={() => {
          setModalData({} as ProjectField);
          setIsModalOpen(true);
        }}
        className="flex items-center px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 mb-4"
      >
        <PlusCircle className="w-5 h-5 mr-2" /> Create
      </button>

      <BackofficeDataTable
        columns={columns}
        data={data}
      />

      {isModalOpen && (
        <ProjectFieldModal
          data={modalData}
          id={modalData?.id || ""}
          open={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          onSave={handleAddEdit}
          userRole={userRole}
          projectId={projectId}
        />
      )}
    </div>
  );
}
