// src/components/tables/UserTable.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Pencil, Trash2 } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import BackofficeDataTable from './BackofficeDataTable.vue'
import UserModal from '@/components/modals/UserModal.vue'
import axiosInstance from '@/lib/axios'
import { formatWibDate } from '@/lib/formatters'
import type { User } from '@/interfaces/User'

const props = defineProps<{ initialData: User[]; companyId: string; userRole?: string }>()
const data = ref<User[]>([...props.initialData])
const modalOpen = ref(false)
const selected = ref<User | null>(null)

const columns = [
  { key: 'name', label: 'Name' },
  { key: 'email', label: 'Email' },
  { key: 'role', label: 'Role' },
  { key: 'lastLoginDate', label: 'Last Login' },
  { key: 'status', label: 'Status' },
  { key: 'actions', label: '' },
]

function openCreate() { selected.value = null; modalOpen.value = true }
function openEdit(u: User) { selected.value = u; modalOpen.value = true }

async function remove(id: string) {
  if (!confirm('Delete this user?')) return
  try {
    await axiosInstance.delete(`/users/${id}`)
    data.value = data.value.filter(u => u.id !== id)
    toast.success('User deleted')
  } catch { toast.error('Failed to delete') }
}

function onSaved(u: User) {
  const i = data.value.findIndex(x => x.id === u.id)
  if (i >= 0) data.value[i] = u; else data.value.unshift(u)
  modalOpen.value = false
}
</script>

<template>
  <div>
    <BackofficeDataTable :data="data as any" :columns="columns">
      <template #actions>
        <button @click="openCreate" class="px-3.5 py-1.5 bg-brand hover:bg-brand-light text-white text-[13px] rounded transition-colors">+ New User</button>
      </template>
      <template #row="{ row }">
        <td class="px-4 py-3 font-medium text-body-text">{{ row.name }}</td>
        <td class="px-4 py-3 text-nav-text text-[13px]">{{ row.email }}</td>
        <td class="px-4 py-3">
          <span class="px-2 py-0.5 bg-sidebar-panel text-nav-text border border-sidebar-border rounded text-[11px] font-mono">{{ row.role }}</span>
        </td>
        <td class="px-4 py-3 text-m-muted text-[13px]">{{ formatWibDate(row.lastLoginDate as string) }}</td>
        <td class="px-4 py-3">
          <span :class="['px-2 py-0.5 rounded text-[11px] font-medium', row.status === 'active' ? 'bg-green-100 text-green-700' : 'bg-sidebar-panel text-m-muted']">{{ row.status }}</span>
        </td>
        <td class="px-4 py-3">
          <div class="flex items-center gap-1">
            <button @click="openEdit(row as any)"
              class="p-1.5 text-m-muted hover:text-nav-active rounded hover:bg-sidebar-panel transition-colors"><Pencil class="w-4 h-4" /></button>
            <button @click="remove(row.id as string)"
              class="p-1.5 text-m-muted hover:text-red-500 rounded hover:bg-red-50 transition-colors"><Trash2 class="w-4 h-4" /></button>
          </div>
        </td>
      </template>
    </BackofficeDataTable>
    <UserModal :open="modalOpen" :data="selected" :company-id="companyId" @close="modalOpen = false" @saved="onSaved" />
  </div>
</template>

// src/components/tables/UserTable.tsx
'use client';

import { useState } from 'react';
import Cookies from 'js-cookie';
import { Trash2, PlusCircle } from 'lucide-react';
import UserModal from '../modals/UserModal';
import User from '@/interfaces/User';
import { BackofficeDataTable } from "@/components/tables/BackofficeDataTable";
import { ColumnDef } from "@tanstack/react-table";
import { formatWibDate } from '@/lib/formatters';
import axiosInstance from '@/lib/axios';

interface Props {
  initialData: User[];
  companyId: string;
  userRole: string;
}

export default function UserTable({ initialData, companyId, userRole }: Props) {
  const [data, setData] = useState(initialData);
  const [loading, setLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalData, setModalData] = useState<User | null>(null);

  const token = Cookies.get('sempoa');

  const columns: ColumnDef<User>[] = [
    {
      header: 'Name',
      cell: ({ row }) => (
        <button
          onClick={() => {
            setModalData(row.original);
            setIsModalOpen(true);
          }}
          className="text-blue-600 underline hover:text-blue-800"
        >
          {row.original.name}
        </button>
      ),
    },
    {
      header: 'Email',
      accessorKey: 'email',
    },
    {
      header: 'Phone',
      accessorKey: 'phoneNumber',
    },
    {
      header: 'Role',
      accessorKey: 'role',
    },
    {
      header: 'Last Login',
      cell: ({ row }) => (
        <div>
          {formatWibDate(row.original.lastLoginDate)}
        </div>
      ),
    },
    {
      header: 'Status',
      cell: ({ row }) => {
        const isDisabled = row.original.status === 'disabled';
        return (
          <span className={`inline-block px-2 py-1 text-xs font-semibold rounded-full ${isDisabled ? 'bg-red-100 text-red-800' : 'bg-green-100 text-green-800'}`}>
            {isDisabled ? 'Disabled' : 'Active'}
          </span>
        );
      },
    },
    {
      header: 'Actions',
      cell: ({ row }) => (
        <div>
          {row.original.role !== 'super' && (
            <button
              onClick={() => handleDisable(row.original.id)}
              className="text-red-500 hover:text-red-700 text-sm p-2 border rounded hover:bg-gray-100"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          )}
        </div>
      ),
    },
  ];

  const fetchData = () => {
    setLoading(true);
    axiosInstance.get(`/companies/${companyId}/users`, {
      headers: { Authorization: `Bearer ${token}` }
    })
      .then(res => {
        setData(res.data.data);
      })
      .catch(err => console.error('Get error:', err))
      .finally(() => setLoading(false));
  };

  const handleDisable = async (id: string) => {
    try {
      await axiosInstance.delete(`/users/${id}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      fetchData();
    } catch (err) {
      console.error('Error deleting:', err);
    }
  };

  return (
    <div className="w-full bg-white rounded-lg p-2">
      <button
        onClick={() => {
          setModalData({
            id: '',
            name: '',
            email: '',
            phoneNumber: '',
            role: '',
            password: '',
            lastLoginDate: '',
            status: 'new',
            companyId: companyId,
          });
          setIsModalOpen(true);
        }}
        className="flex items-center px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 mb-4"
      >
        <PlusCircle className="w-5 h-5 mr-2" /> Create
      </button>

      <BackofficeDataTable
        columns={columns}
        data={data}
      />

      {isModalOpen && (
        <UserModal
          open={isModalOpen}
          data={modalData}
          onClose={() => setIsModalOpen(false)}
          onSave={() => {
            fetchData();
            setIsModalOpen(false);
          }}
        />
      )}
    </div>
  );
}
