// src/components/documents/DocumentFormClient.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { toast } from 'vue-sonner'
import axiosInstance from '@/lib/axios'
import { useAuthStore } from '@/stores/auth'
import type { ProjectField } from '@/interfaces/ProjectField'

const props = defineProps<{
  fields: ProjectField[]
  projectId: string
  parentDocumentId?: string
}>()

const router = useRouter()
const auth = useAuthStore()

const file = ref<File | null>(null)
const docCode = ref('')
const fieldValues = reactive<Record<string, string>>({})
const uploading = ref(false)
const progress = ref(0)

function onFile(e: Event) {
  file.value = (e.target as HTMLInputElement).files?.[0] ?? null
}

function cancelBack() {
  const query: Record<string, string> = {}
  if (props.parentDocumentId) query.parentId = props.parentDocumentId
  router.push({ path: '/documents', query })
}

async function submit() {
  if (!file.value) { toast.error('Please select a file'); return }
  if (!docCode.value.trim()) { toast.error('Document code is required'); return }

  uploading.value = true
  try {
    // Step 1: upload physical file → get fileId
    const fd = new FormData()
    fd.append('file', file.value)
    const fileRes = await axiosInstance.post('/file', fd, {
      headers: { 'Content-Type': 'multipart/form-data' },
      onUploadProgress: e => {
        progress.value = Math.round((e.loaded / (e.total ?? 1)) * 100)
      },
    })
    const fileId = fileRes.data?.id ?? fileRes.data?.fileId

    // Step 2: create document record
    const documentField: Record<string, string> = {}
    for (const f of props.fields) {
      if (fieldValues[f.fieldCode] != null) documentField[f.fieldCode] = fieldValues[f.fieldCode]
    }

    await axiosInstance.post('/documents', {
      docCode: docCode.value.trim().toUpperCase(),
      projectId: props.projectId,
      companyId: auth.user?.companyId,
      fileId,
      type: 'file',
      ...(props.parentDocumentId ? { parentDocumentId: props.parentDocumentId } : {}),
      documentField,
    })

    toast.success('Document uploaded successfully')
    cancelBack()
  } catch (e: any) {
    toast.error(e?.response?.data?.message ?? 'Upload failed')
  } finally {
    uploading.value = false
    progress.value = 0
  }
}
</script>

<template>
  <form @submit.prevent="submit" class="space-y-6 max-w-2xl">
    <!-- Doc Code -->
    <div class="space-y-1.5">
      <label class="text-sm font-medium text-gray-700">Document Code <span class="text-red-500">*</span></label>
      <input v-model="docCode" placeholder="e.g. DWG-ARCH-001" required
        class="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-gray-400 uppercase" />
      <p class="text-xs text-gray-400">Unique code for this document within the project.</p>
    </div>

    <!-- File picker -->
    <div class="space-y-1.5">
      <label class="text-sm font-medium text-gray-700">File <span class="text-red-500">*</span></label>
      <input type="file" @change="onFile" required
        class="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-gray-100 file:text-gray-700 hover:file:bg-gray-200 cursor-pointer" />
    </div>

    <!-- Project fields -->
    <div v-for="f in fields" :key="f.id" class="space-y-1.5">
      <label class="text-sm font-medium text-gray-700">
        {{ f.fieldText }}<span v-if="f.mandatory" class="text-red-500 ml-0.5">*</span>
      </label>
      <select v-if="f.type === 'select'" v-model="fieldValues[f.fieldCode]" :required="f.mandatory"
        class="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-gray-400">
        <option value="">— Select —</option>
        <option v-for="opt in (f.options ?? [])" :key="opt" :value="opt">{{ opt }}</option>
      </select>
      <textarea v-else-if="f.type === 'textarea'" v-model="fieldValues[f.fieldCode]" :required="f.mandatory" rows="3"
        class="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-gray-400" />
      <input v-else v-model="fieldValues[f.fieldCode]"
        :type="f.type === 'number' ? 'number' : f.type === 'date' ? 'date' : 'text'"
        :required="f.mandatory"
        class="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-gray-400" />
    </div>

    <!-- Upload progress -->
    <div v-if="uploading" class="space-y-1">
      <div class="w-full bg-gray-100 rounded-full h-1.5">
        <div class="bg-gray-900 h-1.5 rounded-full transition-all" :style="{ width: `${progress}%` }" />
      </div>
      <p class="text-xs text-gray-400 text-right">{{ progress }}%</p>
    </div>

    <div class="flex gap-3">
      <button type="button" @click="cancelBack"
        class="px-4 py-2 text-sm border border-gray-200 rounded-lg hover:bg-gray-50">Cancel</button>
      <button type="submit" :disabled="uploading"
        class="px-4 py-2 text-sm bg-gray-900 text-white rounded-lg hover:bg-gray-800 disabled:opacity-50">
        {{ uploading ? 'Uploading…' : 'Upload' }}
      </button>
    </div>
  </form>
</template>

// src/components/documents/DocumentFormClient.tsx
'use client';

import { useForm } from 'react-hook-form';
import { useEffect, useState, ChangeEvent } from 'react';
import { useRouter } from 'next/navigation';
import { Document } from '@/interfaces/Document';
import ProjectField from '@/interfaces/ProjectField';
import { Button } from '@/components/ui/button';
import axiosInstance from '@/lib/axios';
import Cookies from 'js-cookie';

interface Props {
  fields: ProjectField[];
  initialData?: Partial<Document>;
}

export default function DocumentFormClient({ fields, initialData = {} }: Props) {
  const router = useRouter();

  const [submitting, setSubmitting] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [uploadedFile, setUploadedFile] = useState<{ id: string; name?: string } | null>(null);

  const {
    register,
    handleSubmit,
    reset,
    setValue,
    formState: { errors },
  } = useForm();

  // Log fields for debug
  useEffect(() => {
  }, [fields]);

  useEffect(() => {
    reset(initialData);
  }, [initialData, reset]);

  const handleFileSelected = async (e: ChangeEvent<HTMLInputElement>) => {
    const token = Cookies.get('sempoa');
    const file = e.target.files?.[0];
    if (!file) return;
    setUploading(true);
    setUploadProgress(0);
    try {
      const form = new FormData();
      form.append('file', file);
      // Note: axiosInstance likely prefixes /api; keep endpoint consistent with axiosInstance usage for /documents
      const res = await axiosInstance.post('/file', form, {
        headers: {
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
          // Let the browser set the multipart boundary
        },
        onUploadProgress: (evt) => {
          if (!evt.total) return;
          const pct = Math.round((evt.loaded * 100) / evt.total);
          setUploadProgress(pct);
        },
      });
      // Support either { data: { id, ... } } or direct { id, ... }
      const payload = res?.data?.data ?? res?.data;
      const fileId = payload?.id ?? payload?.fileId;
      if (fileId) {
        setValue('fileId', fileId, { shouldValidate: true, shouldDirty: true });
        setUploadedFile({ id: fileId, name: file.name });
      } else {
        console.warn('Upload succeeded but no file id returned:', res?.data);
        alert('File uploaded, but no file ID was returned by the server.');
      }
    } catch (err: any) {
      console.error('File upload failed:', err?.response?.data ?? err?.message ?? err);
      alert(err?.response?.data?.message ?? err?.message ?? 'File upload failed');
    } finally {
      setUploading(false);
    }
  };

  const onSubmit = async (formValues: any) => {
    const token = Cookies.get('sempoa');
    setSubmitting(true);
    try {
      const documentField: Record<string, string> = {};
      fields.forEach((field) => {
        documentField[field.fieldCode] = formValues[field.fieldCode];
      });
    
      const payload = {
        ...initialData,
        ...formValues,
        documentField,
      };
    
      const res = await axiosInstance.post('/documents', payload, {
        headers: token ? { Authorization: `Bearer ${token}` } : undefined,
      });
      router.push('/documents');
    } catch (e: any) {
      console.error('Failed to create document:', e?.response?.data ?? e?.message ?? e);
      alert(e?.response?.data?.message ?? e?.message ?? 'Failed to create document');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto px-6 py-3 bg-white rounded">
      <h1 className="text-xl font-semibold mb-6 border-b-2 pb-2 text-gray-500">
        {initialData?.id ? 'Supersede Document' : 'Upload Document'}
      </h1>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
        <input type="hidden" {...register('projectId')} value={initialData.projectId} />
        {/* Document Code */}
        <div>
          <label className="block font-medium mb-3 text-gray-500">Document Code</label>
          <input
            {...register('docCode', { required: true })}
            className="input w-full border rounded px-3 py-1"
            disabled={!!initialData?.id}
          />
          {errors.docCode && <span className="text-red-500 text-sm">Required</span>}
        </div>

        {/* Dynamic Project Fields */}
        {fields
          .filter((f) => f.fieldCode !== 'docCode')
          .map((field) => (
            <div key={field.fieldCode}>
              <label className="block font-medium mb-1 text-gray-400">
                {field.fieldText} {field.mandatory && '*'}
              </label>

              {field.type === 'text' || field.type === 'number' || field.type === 'textarea' ? (
                field.type === 'textarea' ? (
                  <textarea
                    {...register(field.fieldCode, { required: field.mandatory })}
                    className="textarea w-full border rounded px-3 py-1"
                  />
                ) : (
                  <input
                    type={field.type}
                    {...register(field.fieldCode, { required: field.mandatory })}
                    className="input w-full border rounded px-3 py-1"
                  />
                )
              ) : field.type === 'select' && field.options ? (
                <select
                  {...register(field.fieldCode, { required: field.mandatory })}
                  className="select w-full border rounded px-3 py-1"
                >
                  <option value="">Select...</option>
                  {field.options.map((opt) => (
                    <option key={opt} value={opt}>
                      {opt}
                    </option>
                  ))}
                </select>
              ) : field.type === 'checkbox' ? (
                <input
                  type="checkbox"
                  {...register(field.fieldCode)}
                  className="checkbox"
                />
              ) : null}

              {errors[field.fieldCode] && (
                <span className="text-red-500 text-sm">Required</span>
              )}
            </div>
          ))}

        {/* File (optional). Upload creates/returns a fileId; a document may or may not have a file. */}
        <div>
          <label className="block font-medium mb-1 text-gray-400">File (optional)</label>
          {/* Hidden input persists the selected fileId into the form values */}
          <input type="hidden" {...register('fileId', { required: false })} />
          <div className="flex items-center gap-3">
            <input
              type="file"
              onChange={handleFileSelected}
              className="block w-full text-sm text-gray-700 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:hover:bg-blue-100"
              disabled={uploading || submitting}
            />
            {uploadedFile?.id ? (
              <button
                type="button"
                className="text-red-600 hover:text-red-700 text-sm"
                onClick={() => {
                  setUploadedFile(null);
                  setValue('fileId', '', { shouldDirty: true, shouldValidate: true });
                }}
                disabled={uploading || submitting}
              >
                Remove
              </button>
            ) : null}
          </div>
          {uploading ? (
            <div className="text-xs text-gray-500 mt-1">Uploading… {uploadProgress}%</div>
          ) : uploadedFile?.id ? (
            <div className="text-xs text-green-600 mt-1">
              Uploaded: {uploadedFile.name ?? uploadedFile.id} ({uploadedFile.id})
            </div>
          ) : (
            <div className="text-xs text-gray-400 mt-1">
              You can leave this empty. A document can be created without a file.
            </div>
          )}
          {errors.fileId && <span className="text-red-500 text-sm">Required</span>}
        </div>

        {/* Type */}
        <div>
          <label className="block font-medium mb-1 text-gray-400">Type</label>
          <input {...register('type')} className="input w-full border rounded px-3 py-1" />
        </div>

        <div className="flex justify-end space-x-2 pt-4">
          <Button type="button" onClick={() => router.back()} variant="ghost">
            Cancel
          </Button>
          <Button type="submit" disabled={submitting}>{submitting ? 'Saving…' : (initialData?.id ? 'Update' : 'Create')}</Button>
        </div>
      </form>
    </div>
  );
}
